export const ADD_INGRIDIENT_CONSTRUCTOR: 'ADD_INGRIDIENT_CONSTRUCTOR'  = 'ADD_INGRIDIENT_CONSTRUCTOR';
export const ADD_BUN_CONSTRUCTOR: 'ADD_BUN_CONSTRUCTOR' = 'ADD_BUN_CONSTRUCTOR';
export const DELETE_INGRIDIENT_CONSTRUCTOR: 'DELETE_INGRIDIENT_CONSTRUCTOR' = 'DELETE_INGRIDIENT_CONSTRUCTOR';
export const MOVE_INGRIDIENT_CONSTRUCTOR: 'MOVE_INGRIDIENT_CONSTRUCTOR' = 'MOVE_INGRIDIENT_CONSTRUCTOR';
export const GET_COST: 'GET_COST' = 'GET_COST'
export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR'