export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const UPDATE_ORDER = 'UPDATE_ORDER'; 
export const CREATE_ORDER_STARTED = 'CREATE_ORDER_STARTED';
export const CREATE_ORDER_FAILED= 'CREATE_ORDER_FAILED';
export const CLEARE_ORDER= 'CLEARE_ORDER';