export const REGISTER_USER_ERROR: 'REGISTER_USER_ERROR' = 'REGISTER_USER_ERROR';
export const REGISTER_USER_ERROR_NULL: 'REGISTER_USER_ERROR_NULL' = 'REGISTER_USER_ERROR_NULL';
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';

export const LOGIN_USER_ERROR: 'LOGIN_USER_ERROR' = 'LOGIN_USER_ERROR';
export const LOGIN_USER_ERROR_NULL: 'LOGIN_USER_ERROR_NULL' = 'LOGIN_USER_ERROR_NULL';
export const SET_USER: 'SET_USER' = 'SET_USER';

export const UPDATE_TOKEN: 'UPDATE_TOKEN' = 'UPDATE_TOKEN';
export const LOGOUT: 'LOGOUT' = 'LOGOUT';

export const FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR' = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_ERROR_NULL: 'FORGOT_PASSWORD_ERROR_NULL' = 'FORGOT_PASSWORD_ERROR_NULL';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';

export const RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR' = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_ERROR_NULL: 'RESET_PASSWORD_ERROR_NULL' = 'RESET_PASSWORD_ERROR_NULL';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';

export const GET_USER: 'GET_USER' = 'GET_USER';
export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER';
export const UPDATE_ERROR: 'UPDATE_ERROR' = 'UPDATE_ERROR';
export const UPDATE_SUCCESS: 'UPDATE_SUCCESS' = 'UPDATE_SUCCESS';
export const UPDATE_START: 'UPDATE_START' = 'UPDATE_START';